export const initialState = {
  baseFormInfoDate: "",
  baseFormInfoCustomerName: "ahsan",
  baseFormInfoProductName: "sa",
  baseFormInfoUpSizeL: "8",
  baseFormInfoUpSizeW: "8",
  baseFormInfoQuantity1: "40000",
  baseFormInfoQuantity2: "100000",
  baseFormInfoQuantity3: "150000",
  baseFormInfoSpreadSizeL: "8.75",
  baseFormInfoSpreadSizeW: "8.75",
  baseFormInfoMaterial: "e",
  baseFormInfoGsm: "113",
  baseFormInfoPrintSizeL: "18",
  baseFormInfoPrintSizeW: "25",
  baseFormInfoUps: "6",
  baseFormInfoColors: "4",
  baseFormInfoNoOfSide: "1",
  baseFormInfoPostPrint: "12",

  fixedFormInfoDesignMechQuantity: "",
  fixedFormInfoDesignMechCostPerUnit: "1",
  fixedFormInfoDesignMechTotalCost: "2",

  fixedFormInfoFilmsQuantity: "",
  fixedFormInfoFilmsCostPerUnit: "1",
  fixedFormInfoFilmsTotalCost: "2",

  fixedFormInfoDieQuantity: "",
  fixedFormInfoDieCostPerUnit: "8",
  fixedFormInfoDieTotalCost: "2",

  fixedFormInfoTotalFixedCost: "",

  variableFormInfoSheetsQuantity1: "",
  variableFormInfoSheetsReqSheets1: "",
  variableFormInfoSheetsQuantity2: "",
  variableFormInfoSheetsReqSheets2: "",
  variableFormInfoSheetsQuantity3: "",
  variableFormInfoSheetsReqSheets3: "",

  variableFormInfoPlatesCostPerUnit: "600",
  variableFormInfoPlatesQuantity1: "",
  variableFormInfoPlatesTotalCost1: "",
  variableFormInfoPlatesQuantity2: "",
  variableFormInfoPlatesTotalCost2: "",
  variableFormInfoPlatesQuantity3: "",
  variableFormInfoPlatesTotalCost3: "",

  variableFormInfoMaterialCostPerUnit: "190",
  variableFormInfoMaterialQuantity1: "",
  variableFormInfoMaterialTotalCost1: "",
  variableFormInfoMaterialQuantity2: "",
  variableFormInfoMaterialTotalCost2: "",
  variableFormInfoMaterialQuantity3: "",
  variableFormInfoMaterialTotalCost3: "",

  variableFormInfoPrintingCostPerUnit: "700",
  variableFormInfoPrintingQuantity1: "",
  variableFormInfoPrintingTotalCost1: "",
  variableFormInfoPrintingQuantity2: "",
  variableFormInfoPrintingTotalCost2: "",
  variableFormInfoPrintingQuantity3: "",
  variableFormInfoPrintingTotalCost3: "",

  variableFormInfoLaminationUVCostPerUnit: "1",
  variableFormInfoLaminationUVQuantity1: "",
  variableFormInfoLaminationUVTotalCost1: "",
  variableFormInfoLaminationUVQuantity2: "",
  variableFormInfoLaminationUVTotalCost2: "",
  variableFormInfoLaminationUVQuantity3: "",
  variableFormInfoLaminationUVTotalCost3: "",

  variableFormInfoDieCuttingCostPerUnit: "500",
  variableFormInfoDieCuttingQuantity1: "",
  variableFormInfoDieCuttingTotalCost1: "",
  variableFormInfoDieCuttingQuantity2: "",
  variableFormInfoDieCuttingTotalCost2: "",
  variableFormInfoDieCuttingQuantity3: "",
  variableFormInfoDieCuttingTotalCost3: "",

  variableFormInfoMakingCostPerUnit: "400",
  variableFormInfoMakingQuantity1: "",
  variableFormInfoMakingTotalCost1: "",
  variableFormInfoMakingQuantity2: "",
  variableFormInfoMakingTotalCost2: "",
  variableFormInfoMakingQuantity3: "",
  variableFormInfoMakingTotalCost3: "",

  variableFormInfoPackagingDeliveryCostPerUnit: "20",
  variableFormInfoPackagingDeliveryQuantity1: "",
  variableFormInfoPackagingDeliveryTotalCost1: "",
  variableFormInfoPackagingDeliveryQuantity2: "",
  variableFormInfoPackagingDeliveryTotalCost2: "",
  variableFormInfoPackagingDeliveryQuantity3: "",
  variableFormInfoPackagingDeliveryTotalCost3: "",

  totalFormInfoTotalVariableCostQuantity1: "",
  totalFormInfoTotalVariableCostQuantity2: "",
  totalFormInfoTotalVariableCostQuantity3: "",

  totalFormInfoTotalCostQuantity1: "",
  totalFormInfoTotalCostQuantity2: "",
  totalFormInfoTotalCostQuantity3: "",

  totalFormInfoCostPerUnitQuantity1: "",
  totalFormInfoCostPerUnitQuantity2: "",
  totalFormInfoCostPerUnitQuantity3: "",

  totalFormInfoPricePerUnitAfzalPercentage: "2",
  totalFormInfoPricePerUnitAfzalQuantity1: "",
  totalFormInfoPricePerUnitAfzalQuantity2: "",
  totalFormInfoPricePerUnitAfzalQuantity3: "",

  totalFormInfoPricePerUnitImpactPercentage: "25",
  totalFormInfoPricePerUnitImpactQuantity1: "",
  totalFormInfoPricePerUnitImpactQuantity2: "",
  totalFormInfoPricePerUnitImpactQuantity3: "",

  totalFormInfoNetReceivableQuantity1: "",
  totalFormInfoNetReceivableQuantity2: "",
  totalFormInfoNetReceivableQuantity3: "",
  totalFormInfoAmountEarnedQuantity1: "",
  totalFormInfoAmountEarnedQuantity2: "",
  totalFormInfoAmountEarnedQuantity3: "",
  productImage: "",
  validationError1: true,
  validationError2: true,
  validationError3: true,
  validationError4: true,
};
